# Generated by Django 5.1.6 on 2025-04-30 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FacebookPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("user_posted", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("hashtags", models.TextField(blank=True, null=True)),
                ("num_comments", models.IntegerField(default=0)),
                ("date_posted", models.DateTimeField(blank=True, null=True)),
                ("likes", models.IntegerField(default=0)),
                ("photos", models.TextField(blank=True, null=True)),
                ("videos", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("latest_comments", models.TextField(blank=True, null=True)),
                ("post_id", models.CharField(max_length=100)),
                (
                    "discovery_input",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("thumbnail", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "platform_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("engagement_score", models.FloatField(default=0.0)),
                ("tagged_users", models.TextField(blank=True, null=True)),
                ("followers", models.IntegerField(blank=True, null=True)),
                ("posts_count", models.IntegerField(blank=True, null=True)),
                (
                    "profile_image_link",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_paid_partnership", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="facebook_data.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facebook Post",
                "verbose_name_plural": "Facebook Posts",
                "ordering": ["-date_posted"],
                "indexes": [
                    models.Index(
                        fields=["user_posted"], name="facebook_da_user_po_e14b16_idx"
                    ),
                    models.Index(
                        fields=["post_id"], name="facebook_da_post_id_248954_idx"
                    ),
                    models.Index(
                        fields=["date_posted"], name="facebook_da_date_po_ec578b_idx"
                    ),
                ],
                "unique_together": {("post_id", "folder")},
            },
        ),
    ]
