# Generated by Django 5.2 on 2025-09-29 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facebook_data', '0001_initial'),
        ('track_accounts', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='scraping_run',
            field=models.ForeignKey(blank=True, help_text='Associated scraping run', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_folders', to='workflow.scrapingrun'),
        ),
        migrations.AddField(
            model_name='folder',
            name='unified_job_folder',
            field=models.ForeignKey(blank=True, help_text='Linked unified job folder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facebook_platform_folders', to='track_accounts.unifiedrunfolder'),
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='facebook_data.folder'),
        ),
        migrations.AddField(
            model_name='facebookcomment',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Folder containing this comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='facebook_data.folder'),
        ),
        migrations.AddField(
            model_name='commentscrapingjob',
            name='result_folder',
            field=models.ForeignKey(blank=True, help_text='Folder to store scraped comments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraping_jobs', to='facebook_data.folder'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['unified_job_folder'], name='facebook_da_unified_5f007f_idx'),
        ),
        migrations.AddIndex(
            model_name='facebookpost',
            index=models.Index(fields=['user_posted'], name='facebook_da_user_po_e14b16_idx'),
        ),
        migrations.AddIndex(
            model_name='facebookpost',
            index=models.Index(fields=['post_id'], name='facebook_da_post_id_248954_idx'),
        ),
        migrations.AddIndex(
            model_name='facebookpost',
            index=models.Index(fields=['date_posted'], name='facebook_da_date_po_ec578b_idx'),
        ),
        migrations.AddIndex(
            model_name='facebookpost',
            index=models.Index(fields=['page_name'], name='facebook_da_page_na_247581_idx'),
        ),
        migrations.AddIndex(
            model_name='facebookpost',
            index=models.Index(fields=['content_type'], name='facebook_da_content_abd71e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facebookpost',
            unique_together={('post_id', 'folder')},
        ),
        migrations.AddIndex(
            model_name='facebookcomment',
            index=models.Index(fields=['post_id'], name='facebook_da_post_id_7982ea_idx'),
        ),
        migrations.AddIndex(
            model_name='facebookcomment',
            index=models.Index(fields=['user_id'], name='facebook_da_user_id_f2ff91_idx'),
        ),
        migrations.AddIndex(
            model_name='facebookcomment',
            index=models.Index(fields=['date_created'], name='facebook_da_date_cr_34d884_idx'),
        ),
        migrations.AddIndex(
            model_name='facebookcomment',
            index=models.Index(fields=['comment_id'], name='facebook_da_comment_f9357f_idx'),
        ),
    ]
