# Generated by Django 5.1.6 on 2025-04-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpost",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="active_ads_urls",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="attachments",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="audio",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="avatar_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="count_reactions_type",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="days_range",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="delegate_page_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="error_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="external_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="following",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="from_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="has_handshake",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="header_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="include_profile_data",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="input",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="is_page",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="is_sponsored",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="length",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="link_description_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="num_likes_type",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="num_of_posts",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="num_shares",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="original_post",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="other_posts_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="page_category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="page_creation_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="page_email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="page_external_website",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="page_followers",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="page_intro",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="page_is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="page_likes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="page_logo",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="page_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="page_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="page_price_range",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="page_reviewers_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="page_reviews_score",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="page_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="post_external_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="post_external_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="post_external_title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="post_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="post_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="posts_to_not_include",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="profile_handle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="profile_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="shortcode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="sponsor_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="until_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="user_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="user_username_raw",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="video_view_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="warning",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="warning_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="facebookpost",
            name="user_posted",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="facebookpost",
            index=models.Index(
                fields=["page_name"], name="facebook_da_page_na_247581_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facebookpost",
            index=models.Index(
                fields=["content_type"], name="facebook_da_content_abd71e_idx"
            ),
        ),
    ]
