# Generated by Django 5.1.6 on 2025-04-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "facebook_data",
            "0002_facebookpost_about_facebookpost_active_ads_urls_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="facebookpost",
            old_name="attachments",
            new_name="attachments_data",
        ),
    ]
