# Generated by Django 5.1.6 on 2025-04-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_data", "0003_rename_attachments_facebookpost_attachments_data"),
    ]

    operations = []
