# Generated by Django 5.1.6 on 2025-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_data", "0004_auto_20250430_1942"),
    ]

    operations = [
        # Field already exists in the model, so we remove the operation to avoid duplicate column error
    ]
