# Generated by Django 5.1.6 on 2025-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_data", "0004_auto_20250430_1942"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpost",
            name="user_posted",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
