# Generated by Django 5.1.6 on 2025-04-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_data", "0005_add_user_posted_field"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="facebookpost",
            index=models.Index(fields=["user_posted"], name="facebook_da_user_po_9d9e24_idx"),
        ),
        migrations.AddIndex(
            model_name="facebookpost",
            index=models.Index(fields=["post_id"], name="facebook_da_post_id_3d6220_idx"),
        ),
        migrations.AddIndex(
            model_name="facebookpost",
            index=models.Index(fields=["date_posted"], name="facebook_da_date_po_0f3432_idx"),
        ),
        migrations.AddIndex(
            model_name="facebookpost",
            index=models.Index(fields=["page_name"], name="facebook_da_page_na_e289e3_idx"),
        ),
        migrations.AddIndex(
            model_name="facebookpost",
            index=models.Index(fields=["content_type"], name="facebook_da_content_abd71e_idx"),
        ),
    ]
