# Generated by Django 5.1.6 on 2025-04-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_data", "0005_add_user_posted_field"),
    ]

    operations = [
        # Indexes already exist in the model class Meta, so we're removing these operations to avoid errors
    ]
