# Generated by Django 5.1.6 on 2025-04-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_data", "0006_add_missing_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpost",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
