# Generated by Django 5.1.6 on 2025-04-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_data", "0006_add_missing_indexes"),
    ]

    operations = [
        # Description field already exists in the model, so we're removing this operation to avoid errors
    ]
