# Generated by Django 5.1.6 on 2025-04-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_data", "0007_add_description_field"),
    ]

    operations = [
        # These fields already exist in the model, so we're removing these operations to avoid errors
    ]
