# Generated by Django 5.1.6 on 2025-04-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_data", "0007_add_description_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpost",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="hashtags",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
