# Generated by Django 5.1.6 on 2025-04-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_data", "0008_ensure_remaining_fields"),
    ]

    operations = [
        # Content_type field already exists in the model, so we're removing this operation to avoid errors
    ]
