# Generated by Django 5.1.6 on 2025-04-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_data", "0008_ensure_remaining_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpost",
            name="content_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
