# Generated by Django 5.1.6 on 2025-04-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_data", "0009_add_content_type_field"),
    ]

    operations = [
        # count_reactions_type field already exists in the model, so we're removing this operation to avoid errors
    ]
