# Generated by Django 5.1.6 on 2025-04-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_data", "0009_add_content_type_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpost",
            name="count_reactions_type",
            field=models.TextField(blank=True, null=True),
        ),
    ]
