# Generated by Django 5.1.6 on 2025-04-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_data", "0010_add_reactions_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpost",
            name="followers",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="latest_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="profile_image_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="tagged_users",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="posts_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="discovery_input",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="is_paid_partnership",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="engagement_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="platform_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
