# Generated by Django 5.1.6 on 2025-04-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_data", "0010_add_reactions_field"),
    ]

    operations = [
        # All these fields already exist in the model, so we're removing these operations to avoid errors
    ]
