# Generated by Django 5.1.6 on 2025-05-11 10:38

from django.db import migrations, models


def check_user_posted_exists(apps, schema_editor):
    # This is a no-op function that will be called
    # Simply checking the field but not actually creating it
    # as the real field already exists in the model
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_data", "0011_add_remaining_fields"),
    ]

    operations = [
        migrations.RunPython(
            check_user_posted_exists,
            reverse_code=migrations.RunPython.noop
        ),
    ]
