# Generated by Django 5.2 on 2025-05-28 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_data', '0015_commentscrapingjob_result_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookcomment',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Folder containing this comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='facebook_data.folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='category',
            field=models.CharField(choices=[('posts', 'Posts & Reels'), ('comments', 'Comments')], default='posts', help_text='Type of content stored in this folder', max_length=20),
        ),
    ]
