# Generated by Django 5.2 on 2025-05-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_data', '0016_add_folder_category_and_comment_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='category',
            field=models.CharField(choices=[('posts', 'Posts'), ('reels', 'Reels'), ('comments', 'Comments')], default='posts', help_text='Type of content stored in this folder', max_length=20),
        ),
    ]
