# Generated by Django 5.2 on 2025-08-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_data', '0018_folder_folder_type_folder_parent_folder_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='folder',
            name='facebook_da_folder__60c46a_idx',
        ),
        migrations.RemoveIndex(
            model_name='folder',
            name='facebook_da_parent__32bea1_idx',
        ),
    ]
