# Generated by Django 5.2 on 2025-08-08 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_data', '0021_alter_folder_folder_type'),
        ('track_accounts', '0017_alter_unifiedrunfolder_folder_type'),
        ('users', '0006_service_platform_platformservice'),
        ('workflow', '0007_scheduledscrapingtask_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='unified_job_folder',
            field=models.ForeignKey(blank=True, help_text='Linked unified job folder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facebook_platform_folders', to='track_accounts.unifiedrunfolder'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['unified_job_folder'], name='facebook_da_unified_5f007f_idx'),
        ),
    ]
