# Generated by Django 5.2 on 2025-08-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_data', '0024_facebookpost_job_folder_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='facebookpost',
            name='facebook_da_scrape__3db206_idx',
        ),
        migrations.RemoveIndex(
            model_name='facebookpost',
            name='facebook_da_scraper_012878_idx',
        ),
        migrations.RemoveIndex(
            model_name='facebookpost',
            name='facebook_da_webhook_4c9fd0_idx',
        ),
        migrations.RemoveIndex(
            model_name='facebookpost',
            name='facebook_da_job_fol_150c07_idx',
        ),
        migrations.RemoveIndex(
            model_name='folder',
            name='facebook_da_scrape__0c34cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='folder',
            name='facebook_da_scrapin_fbb1be_idx',
        ),
        migrations.RemoveField(
            model_name='facebookpost',
            name='job_folder',
        ),
        migrations.RemoveField(
            model_name='facebookpost',
            name='scrape_job',
        ),
        migrations.RemoveField(
            model_name='facebookpost',
            name='scraper_request',
        ),
        migrations.RemoveField(
            model_name='facebookpost',
            name='webhook_received_at',
        ),
        migrations.RemoveField(
            model_name='facebookpost',
            name='webhook_snapshot_id',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='scrape_job',
        ),
    ]
