# Generated by Django 5.1.6 on 2025-04-24 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrackAccountFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Track Account Folder",
                "verbose_name_plural": "Track Account Folders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrackAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("iac_no", models.CharField(max_length=100, unique=True)),
                ("facebook_id", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "instagram_id",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("linkedin_id", models.URLField(blank=True, max_length=500, null=True)),
                ("tiktok_id", models.URLField(blank=True, max_length=500, null=True)),
                ("other_social_media", models.TextField(blank=True, null=True)),
                (
                    "risk_classification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("close_monitoring", models.BooleanField(default=False)),
                (
                    "posting_frequency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="track_accounts.trackaccountfolder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Track Account",
                "verbose_name_plural": "Track Accounts",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="track_accou_name_82231c_idx"),
                    models.Index(
                        fields=["iac_no"], name="track_accou_iac_no_e90a8e_idx"
                    ),
                    models.Index(
                        fields=["risk_classification"],
                        name="track_accou_risk_cl_cf6f9e_idx",
                    ),
                ],
            },
        ),
    ]
