# Generated by Django 5.2 on 2025-09-29 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFolderIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_code', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], max_length=20)),
                ('service_code', models.CharField(choices=[('posts', 'Posts'), ('reels', 'Reels'), ('comments', 'Comments'), ('profiles', 'Profiles')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrackSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], max_length=20, null=True)),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=500, null=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=500, null=True)),
                ('tiktok_link', models.URLField(blank=True, max_length=500, null=True)),
                ('other_social_media', models.TextField(blank=True, null=True)),
                ('url_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Track Source',
                'verbose_name_plural': 'Track Sources',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedRunFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('folder_type', models.CharField(choices=[('run', 'Run'), ('platform', 'Platform'), ('service', 'Service'), ('job', 'Job'), ('content', 'Content')], default='content', max_length=20)),
                ('category', models.CharField(choices=[('posts', 'Posts'), ('reels', 'Reels'), ('comments', 'Comments')], default='posts', max_length=20)),
                ('platform_code', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], max_length=20, null=True)),
                ('service_code', models.CharField(blank=True, choices=[('posts', 'Posts'), ('reels', 'Reels'), ('comments', 'Comments'), ('profiles', 'Profiles')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unified Run Folder',
                'verbose_name_plural': 'Unified Run Folders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('source_folders', models.TextField(blank=True, null=True)),
                ('total_posts', models.IntegerField(default=0)),
                ('matched_posts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_folders', to='users.project')),
            ],
            options={
                'verbose_name': 'Report Folder',
                'verbose_name_plural': 'Report Folders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('entity', models.CharField(blank=True, max_length=255, null=True)),
                ('posting_date', models.DateTimeField(blank=True, null=True)),
                ('platform_type', models.CharField(blank=True, max_length=50, null=True)),
                ('post_url', models.URLField(blank=True, max_length=500, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, max_length=100, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('post_id', models.CharField(blank=True, max_length=100, null=True)),
                ('track_source_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='track_accounts.reportfolder')),
            ],
            options={
                'verbose_name': 'Report Entry',
                'verbose_name_plural': 'Report Entries',
                'ordering': ['-posting_date'],
            },
        ),
    ]
