# Generated by Django 5.1.6 on 2025-04-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackaccount",
            name="facebook_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trackaccount",
            name="instagram_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trackaccount",
            name="linkedin_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trackaccount",
            name="tiktok_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
