# Generated by Django 5.2 on 2025-09-29 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track_accounts', '0001_initial'),
        ('users', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefolderindex',
            name='scraping_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_folder_indexes', to='workflow.scrapingrun'),
        ),
        migrations.AddField(
            model_name='tracksource',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_sources', to='users.project'),
        ),
        migrations.AddField(
            model_name='unifiedrunfolder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='track_accounts.unifiedrunfolder'),
        ),
        migrations.AddField(
            model_name='unifiedrunfolder',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_run_folders', to='users.project'),
        ),
        migrations.AddField(
            model_name='unifiedrunfolder',
            name='scraping_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_folders', to='workflow.scrapingrun'),
        ),
        migrations.AddField(
            model_name='servicefolderindex',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexed_service_folder', to='track_accounts.unifiedrunfolder'),
        ),
        migrations.AddIndex(
            model_name='tracksource',
            index=models.Index(fields=['name'], name='track_accou_name_5dae6b_idx'),
        ),
        migrations.AddIndex(
            model_name='tracksource',
            index=models.Index(fields=['created_at'], name='track_accou_created_35b135_idx'),
        ),
        migrations.AddIndex(
            model_name='tracksource',
            index=models.Index(fields=['platform'], name='track_accou_platfor_b8d9f2_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedrunfolder',
            index=models.Index(fields=['scraping_run', 'folder_type'], name='track_accou_scrapin_49d942_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedrunfolder',
            index=models.Index(fields=['scraping_run', 'folder_type', 'platform_code', 'service_code'], name='track_accou_scrapin_8c2da3_idx'),
        ),
        migrations.AddConstraint(
            model_name='unifiedrunfolder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('folder_type', 'platform'), ('platform_code__isnull', False)), models.Q(('folder_type', 'platform'), _negated=True), _connector='OR'), name='ck_unified_platform_requires_platform_code'),
        ),
        migrations.AddConstraint(
            model_name='unifiedrunfolder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('folder_type', 'service'), ('platform_code__isnull', False), ('service_code__isnull', False)), models.Q(('folder_type', 'service'), _negated=True), _connector='OR'), name='ck_unified_service_requires_platform_and_service_code'),
        ),
        migrations.AddIndex(
            model_name='servicefolderindex',
            index=models.Index(fields=['scraping_run', 'platform_code', 'service_code'], name='track_accou_scrapin_d41282_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicefolderindex',
            unique_together={('scraping_run', 'platform_code', 'service_code')},
        ),
    ]
