# Generated by Django 5.2 on 2025-10-05 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_accounts', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('folder_type', models.CharField(choices=[('company', 'Company Sources'), ('competitor', 'Competitor Sources'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_folders', to='users.project')),
            ],
            options={
                'verbose_name': 'Source Folder',
                'verbose_name_plural': 'Source Folders',
                'ordering': ['folder_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tracksource',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='track_accounts.sourcefolder'),
        ),
        migrations.AddIndex(
            model_name='sourcefolder',
            index=models.Index(fields=['project', 'folder_type'], name='track_accou_project_cb8b16_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcefolder',
            index=models.Index(fields=['created_at'], name='track_accou_created_76d076_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sourcefolder',
            unique_together={('project', 'name')},
        ),
    ]
