# Generated by Django 5.1.6 on 2025-04-25 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track_accounts", "0002_trackaccount_facebook_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("source_folders", models.TextField(blank=True, null=True)),
                ("total_posts", models.IntegerField(default=0)),
                ("matched_posts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Report Folder",
                "verbose_name_plural": "Report Folders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("iac_no", models.CharField(blank=True, max_length=100, null=True)),
                ("entity", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "close_monitoring",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("posting_date", models.DateTimeField(blank=True, null=True)),
                (
                    "platform_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("post_url", models.URLField(blank=True, max_length=500, null=True)),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("keywords", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("post_id", models.CharField(blank=True, max_length=100, null=True)),
                ("track_account_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="track_accounts.reportfolder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Entry",
                "verbose_name_plural": "Report Entries",
                "ordering": ["-posting_date"],
            },
        ),
    ]
