# Generated by Django 5.1.6 on 2025-04-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track_accounts", "0003_reportfolder_reportentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportentry",
            name="sn",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
