# Generated by Django 5.1.6 on 2025-05-13 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track_accounts", "0004_reportentry_sn"),
        ("users", "0002_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportfolder",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_folders",
                to="users.project",
            ),
        ),
        migrations.AddField(
            model_name="trackaccountfolder",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_account_folders",
                to="users.project",
            ),
        ),
    ]
