# Generated by Django 5.1.6 on 2025-05-14 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track_accounts", "0005_reportfolder_project_trackaccountfolder_project"),
        ("users", "0003_project_authorized_users_project_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackaccount",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_accounts",
                to="users.project",
            ),
        ),
    ]
