# Generated by Django 5.1.6 on 2025-05-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("track_accounts", "0006_trackaccount_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackaccount",
            name="folder",
        ),
        migrations.DeleteModel(
            name="TrackAccountFolder",
        ),
    ]
