# Generated by Django 5.2 on 2025-05-30 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_accounts', '0008_update_social_media_fields'),
        ('users', '0005_remove_organization_slug_remove_project_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportentry',
            old_name='track_account_id',
            new_name='track_source_id',
        ),
        migrations.CreateModel(
            name='TrackSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('iac_no', models.CharField(max_length=100, unique=True)),
                ('facebook_link', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=500, null=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=500, null=True)),
                ('tiktok_link', models.URLField(blank=True, max_length=500, null=True)),
                ('other_social_media', models.TextField(blank=True, null=True)),
                ('risk_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('close_monitoring', models.BooleanField(default=False)),
                ('posting_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_sources', to='users.project')),
            ],
            options={
                'verbose_name': 'Track Source',
                'verbose_name_plural': 'Track Sources',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='TrackAccount',
        ),
        migrations.AddIndex(
            model_name='tracksource',
            index=models.Index(fields=['name'], name='track_accou_name_5dae6b_idx'),
        ),
        migrations.AddIndex(
            model_name='tracksource',
            index=models.Index(fields=['iac_no'], name='track_accou_iac_no_3db030_idx'),
        ),
        migrations.AddIndex(
            model_name='tracksource',
            index=models.Index(fields=['risk_classification'], name='track_accou_risk_cl_6a4e41_idx'),
        ),
    ]
