# Generated by Django 5.2 on 2025-05-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_accounts', '0010_remove_unused_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tracksource',
            name='track_accou_iac_no_3db030_idx',
        ),
        migrations.RemoveIndex(
            model_name='tracksource',
            name='track_accou_risk_cl_6a4e41_idx',
        ),
    ]
