# Generated by Django 5.2 on 2025-08-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_accounts', '0010_remove_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksource',
            name='service_name',
            field=models.CharField(blank=True, help_text='Service name for this source', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tracksource',
            name='url_count',
            field=models.IntegerField(default=0, help_text='Number of URLs associated with this source'),
        ),
    ]
