# Generated by Django 5.2 on 2025-08-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_accounts', '0011_tracksource_service_name_tracksource_url_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracksource',
            name='service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tracksource',
            name='url_count',
            field=models.IntegerField(default=0),
        ),
    ]
