# Generated by Django 5.2 on 2025-08-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_accounts', '0012_alter_tracksource_service_name_and_more'),
        ('users', '0006_service_platform_platformservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracksource',
            options={'ordering': ['created_at'], 'verbose_name': 'Track Source', 'verbose_name_plural': 'Track Sources'},
        ),
        migrations.AddIndex(
            model_name='tracksource',
            index=models.Index(fields=['created_at'], name='track_accou_created_35b135_idx'),
        ),
    ]
