# Generated by Django 5.2 on 2025-08-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_accounts', '0013_alter_tracksource_options_and_more'),
        ('users', '0006_service_platform_platformservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksource',
            name='platform',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='tracksource',
            index=models.Index(fields=['platform'], name='track_accou_platfor_b8d9f2_idx'),
        ),
    ]
