# Generated by Django 5.2 on 2025-08-06 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_accounts', '0014_tracksource_platform_and_more'),
        ('users', '0006_service_platform_platformservice'),
        ('workflow', '0006_remove_scrapingrunfolder_scraping_run_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedRunFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('folder_type', models.CharField(choices=[('run', 'Run'), ('service', 'Service'), ('content', 'Content')], default='content', max_length=20)),
                ('category', models.CharField(choices=[('posts', 'Posts'), ('reels', 'Reels'), ('comments', 'Comments')], default='posts', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='track_accounts.unifiedrunfolder')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_run_folders', to='users.project')),
                ('scraping_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_folders', to='workflow.scrapingrun')),
            ],
            options={
                'verbose_name': 'Unified Run Folder',
                'verbose_name_plural': 'Unified Run Folders',
                'ordering': ['-created_at'],
            },
        ),
    ]
