# Generated by Django 5.2 on 2025-08-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_accounts', '0015_unifiedrunfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedrunfolder',
            name='folder_type',
            field=models.CharField(choices=[('run', 'Run'), ('service', 'Service'), ('content', 'Content'), ('job', 'Job')], default='content', max_length=20),
        ),
    ]
