# Generated by Django 5.2 on 2025-08-09 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0019_scrapeoutput_alter_brightdataconfig_unique_together_and_more'),
        ('track_accounts', '0018_servicefolderindex_unifiedrunfolder_platform_code_and_more'),
        ('users', '0006_service_platform_platformservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksource',
            name='brightdata_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_sources', to='brightdata_integration.brightdataconfig'),
        ),
        migrations.AddField(
            model_name='tracksource',
            name='platform_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_sources', to='users.platformservice'),
        ),
        migrations.AddField(
            model_name='tracksource',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
