# Generated by Django 5.2 on 2025-08-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_accounts', '0019_tracksource_brightdata_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracksource',
            name='brightdata_config',
        ),
        migrations.RemoveField(
            model_name='tracksource',
            name='platform_service',
        ),
        migrations.RemoveField(
            model_name='tracksource',
            name='source_url',
        ),
    ]
