# Generated by Django 5.2 on 2025-08-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_accounts', '0020_remove_tracksource_brightdata_config_and_more'),
        ('users', '0006_service_platform_platformservice'),
        ('workflow', '0012_remove_webhook_status_field'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unifiedrunfolder',
            name='ck_unified_platform_requires_platform_code',
        ),
        migrations.RemoveConstraint(
            model_name='unifiedrunfolder',
            name='ck_unified_service_requires_platform_and_service_code',
        ),
        migrations.AddField(
            model_name='unifiedrunfolder',
            name='job_metadata',
            field=models.JSONField(blank=True, help_text='Stores job-specific metadata for reliable linking (batch_job_id, request_id, etc.)', null=True),
        ),
        migrations.AddIndex(
            model_name='unifiedrunfolder',
            index=models.Index(fields=['job_metadata'], name='track_accou_job_met_871f10_idx'),
        ),
        migrations.AddConstraint(
            model_name='unifiedrunfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('folder_type', 'service')), fields=('scraping_run', 'folder_type', 'platform_code', 'service_code'), name='unique_service_folder_per_run'),
        ),
        migrations.AddConstraint(
            model_name='unifiedrunfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('folder_type', 'platform')), fields=('scraping_run', 'folder_type', 'platform_code'), name='unique_platform_folder_per_run'),
        ),
    ]
