# Generated by Django 5.2 on 2025-08-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_accounts', '0021_add_job_metadata_field'),
        ('users', '0006_service_platform_platformservice'),
        ('workflow', '0012_remove_webhook_status_field'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unifiedrunfolder',
            name='unique_service_folder_per_run',
        ),
        migrations.RemoveConstraint(
            model_name='unifiedrunfolder',
            name='unique_platform_folder_per_run',
        ),
        migrations.RemoveIndex(
            model_name='unifiedrunfolder',
            name='track_accou_job_met_871f10_idx',
        ),
        migrations.RemoveField(
            model_name='unifiedrunfolder',
            name='job_metadata',
        ),
        migrations.AddConstraint(
            model_name='unifiedrunfolder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('folder_type', 'platform'), ('platform_code__isnull', False)), models.Q(('folder_type', 'platform'), _negated=True), _connector='OR'), name='ck_unified_platform_requires_platform_code'),
        ),
        migrations.AddConstraint(
            model_name='unifiedrunfolder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('folder_type', 'service'), ('platform_code__isnull', False), ('service_code__isnull', False)), models.Q(('folder_type', 'service'), _negated=True), _connector='OR'), name='ck_unified_service_requires_platform_and_service_code'),
        ),
    ]
