"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-k14j23-+4o*h)26ms8k#ghmv*kglz!hsf^h%sac1^sy7w6f2qw"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Force DEBUG mode to be permissive

ALLOWED_HOSTS = ['*']  # Allow all hosts


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party apps
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",

    # Local apps
    "users",
    "reports",
    "analytics",
    "data_collector",
    "query_builder",
    "instagram_data",
    "facebook_data",
    "track_accounts",
    "linkedin_data",
    "tiktok_data",
    "apify_integration",
    "brightdata_integration",  # New BrightData integration
    "chat",
    "workflow",
]

MIDDLEWARE = [
    "users.middleware.CustomCsrfMiddleware",  # 🚨 CSRF BYPASS FIRST - OVERRIDES EVERYTHING
    "corsheaders.middleware.CorsMiddleware",  # CORS second
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Enable WhiteNoise for static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",  # NEVER ENABLE - COMPLETELY DISABLED
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # "django.middleware.clickjacking.XFrameOptionsMiddleware",  # Disable X-Frame protection
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configure database based on environment
import dj_database_url
import json

# Default to SQLite for development
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Upsun database configuration
if 'PLATFORM_RELATIONSHIPS' in os.environ:
    try:
        import base64
        relationships = json.loads(base64.b64decode(os.environ['PLATFORM_RELATIONSHIPS']).decode('utf-8'))
        if 'database' in relationships:
            db_settings = relationships['database'][0]
            DATABASES['default'] = {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': db_settings['path'],
                'USER': db_settings['username'],
                'PASSWORD': db_settings['password'],
                'HOST': db_settings['host'],
                'PORT': db_settings['port'],
                'OPTIONS': {
                    'sslmode': 'require',
                },
            }
    except (ValueError, KeyError, IndexError):
        pass

# Override with PostgreSQL if DATABASE_URL is provided (production)
elif os.getenv('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.parse(os.getenv('DATABASE_URL'))
    # Add SSL requirement for production
    DATABASES['default']['OPTIONS'] = {
        'sslmode': 'require',
    }
elif os.getenv('DATABASE_HOST'):
    # Manual PostgreSQL configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DATABASE_NAME', 'trackfutura'),
            'USER': os.getenv('DATABASE_USER', 'postgres'),
            'PASSWORD': os.getenv('DATABASE_PASSWORD', ''),
            'HOST': os.getenv('DATABASE_HOST', 'localhost'),
            'PORT': os.getenv('DATABASE_PORT', '5432'),
            'OPTIONS': {
                'sslmode': 'prefer',
            },
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Frontend static files - include the built React app
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '..', 'frontend', 'dist'),  # Include frontend build directory
]

# Enable WhiteNoise for static file serving in production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# WhiteNoise configuration
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# For development, you can use console backend to see emails in console
# Uncomment the line below to use console backend for development
# if DEBUG:
#     EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Completely disable custom logging to prevent file handler errors
# Use Django defaults only for deployment compatibility
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
    },
}

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'UNAUTHENTICATED_USER': 'django.contrib.auth.models.AnonymousUser',
    'UNAUTHENTICATED_TOKEN': None,
}

# 🚨 MAXIMUM PERMISSIVE CORS - ALLOW ABSOLUTELY EVERYTHING 🚨
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_HEADERS = True
# CORS_REPLACE_HTTPS_REFERER is deprecated and removed

# Specifically allow your Upsun domain and any variations
CORS_ALLOWED_ORIGINS = [
    "https://api.upsun-deployment-xiwfmii-inhoolfrqniuu.eu-5.platformsh.site",
    "https://upsun-deployment-xiwfmii-inhoolfrqniuu.eu-5.platformsh.site",
    "http://localhost:3000",
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:5175",
    "http://localhost:5185",
    "http://localhost:8000",
    "http://localhost:8080",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:5175",
    "http://127.0.0.1:5185",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:8080",
]
CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'access-control-allow-origin',
    'access-control-allow-credentials',
    'access-control-allow-headers',
    'access-control-allow-methods',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_PREFLIGHT_MAX_AGE = 86400
CORS_EXPOSE_HEADERS = []
CORS_ALLOW_PRIVATE_NETWORK = True

# 🚨 COMPLETE CSRF BYPASS - NO ORIGIN CHECKING 🚨
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = None
CSRF_USE_SESSIONS = False

# 🚨 NUCLEAR CSRF DISABLE - OVERRIDE DJANGO CORE 🚨

# Completely disable CSRF at Django's core level
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = None
CSRF_USE_SESSIONS = False

# Override Django's CSRF settings to bypass everything
import django.middleware.csrf
# Monkey patch Django's CSRF middleware to do nothing
original_process_view = django.middleware.csrf.CsrfViewMiddleware.process_view
def dummy_process_view(self, request, callback, callback_args, callback_kwargs):
    """Dummy CSRF process_view that does nothing"""
    return None
django.middleware.csrf.CsrfViewMiddleware.process_view = dummy_process_view

# Trust all origins (Django 4.0+ requires scheme prefixes)
CSRF_TRUSTED_ORIGINS = [
    # Upsun deployment URLs
    "https://api.upsun-deployment-xiwfmii-inhoolfrqniuu.eu-5.platformsh.site",
    "https://upsun-deployment-xiwfmii-inhoolfrqniuu.eu-5.platformsh.site",
    # Local development URLs
    "http://localhost:3000",
    "http://localhost:5173",
    "http://localhost:5185",
    "http://localhost:8000",
    "http://localhost:8080",
    "https://localhost:3000",
    "https://localhost:5173",
    "https://localhost:5185",
    "https://localhost:8000",
    "https://localhost:8080",
    # Common localhost variants
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5185",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:8080",
    "https://127.0.0.1:3000",
    "https://127.0.0.1:5173",
    "https://127.0.0.1:5185",
    "https://127.0.0.1:8000",
    "https://127.0.0.1:8080",
]

# Never fail CSRF
def never_fail_csrf(request, reason=""):
    """Custom CSRF failure view that never fails"""
    return None

CSRF_FAILURE_VIEW = never_fail_csrf

# Add dynamic origins for Upsun
DYNAMIC_CORS_ORIGINS = []
if os.getenv('PLATFORM_APPLICATION_NAME'):
    # Add all possible Upsun/Platform.sh patterns
    app_name = os.getenv('PLATFORM_APPLICATION_NAME', 'app')
    project_id = os.getenv('PLATFORM_PROJECT', '')
    environment = os.getenv('PLATFORM_ENVIRONMENT', 'main')

    if project_id:
        # All possible domain patterns
        base_patterns = [
            f"https://{app_name}-{project_id}.{environment}.platformsh.site",
            f"https://api.{app_name}-{project_id}.{environment}.platformsh.site",
            f"https://{app_name}-{project_id}.{environment}.upsun.app",
            f"https://api.{app_name}-{project_id}.{environment}.upsun.app",
            f"https://{project_id}.{environment}.platformsh.site",
            f"https://{project_id}.{environment}.upsun.app",
        ]
        DYNAMIC_CORS_ORIGINS.extend(base_patterns)
        CSRF_TRUSTED_ORIGINS.extend(base_patterns)

    # Also get from Platform routes if available
    platform_routes = os.getenv('PLATFORM_ROUTES')
    if platform_routes:
        try:
            import json
            routes = json.loads(platform_routes)
            for route_url in routes.keys():
                if route_url.startswith(('http://', 'https://')):
                    clean_url = route_url.rstrip('/')
                    DYNAMIC_CORS_ORIGINS.append(clean_url)
                    CSRF_TRUSTED_ORIGINS.append(clean_url)
        except (json.JSONDecodeError, AttributeError):
            pass

# Override CORS origins to include dynamic ones
CORS_ALLOWED_ORIGINS = DYNAMIC_CORS_ORIGINS + [
    'http://localhost:3000',
    'http://localhost:5173',
    'http://localhost:5185',
    'http://localhost:8000',
    'http://localhost:8080',
    'https://localhost:3000',
    'https://localhost:5173',
    'https://localhost:5185',
    'https://localhost:8000',
    'https://localhost:8080',
]

# ✅ CSRF COMPLETELY DISABLED - NO MORE DUPLICATE SETTINGS

# Session security settings - make permissive
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = None
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Disable ALL security headers completely
SECURE_SSL_REDIRECT = False
SECURE_PROXY_SSL_HEADER = None
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_CONTENT_TYPE_NOSNIFF = False
SECURE_BROWSER_XSS_FILTER = False
SECURE_REFERRER_POLICY = None

# Completely disable X-Frame-Options
X_FRAME_OPTIONS = None

# Additional deployment settings
USE_HTTPS = False
SECURE_REDIRECT_EXEMPT = []  # Empty list - no regex patterns needed

# Force all requests to be treated as secure if needed
if os.getenv('PLATFORM_APPLICATION_NAME'):
    # On Upsun, we might be behind a proxy, but don't enforce security
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # But still don't redirect or enforce
    SECURE_SSL_REDIRECT = False

# Apify Integration Settings
APIFY_API_TOKEN = os.getenv('APIFY_API_TOKEN', '')

# Production/Upsun settings.
if (os.getenv('PLATFORM_APPLICATION_NAME') is not None):
    # Keep DEBUG True for now to avoid issues
    DEBUG = True

    # Static files for production - match Upsun mount path
    STATIC_ROOT = '/app/staticfiles'
    
    # Frontend static files in production
    STATICFILES_DIRS = [
        '/app/frontend/dist',  # Include frontend build directory in production
    ]

    # Secret Key.
    if (os.getenv('PLATFORM_PROJECT_ENTROPY') is not None):
        SECRET_KEY = os.getenv('PLATFORM_PROJECT_ENTROPY')

    # Allow all hosts for deployment
    ALLOWED_HOSTS = ['*']

    # Production database configuration.
    if (os.getenv('PLATFORM_ENVIRONMENT') is not None):
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.getenv('DATABASE_PATH'),
                'USER': os.getenv('DATABASE_USERNAME'),
                'PASSWORD': os.getenv('DATABASE_PASSWORD'),
                'HOST': os.getenv('DATABASE_HOST'),
                'PORT': os.getenv('DATABASE_PORT'),
            },
            'sqlite': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
            }
        }

# Add webhook configuration
WEBHOOK_RATE_LIMIT = os.environ.get('WEBHOOK_RATE_LIMIT', 100)  # requests per minute
WEBHOOK_MAX_TIMESTAMP_AGE = os.environ.get('WEBHOOK_MAX_TIMESTAMP_AGE', 300)  # 5 minutes
WEBHOOK_MAX_EVENTS = os.environ.get('WEBHOOK_MAX_EVENTS', 1000)
WEBHOOK_METRICS_RETENTION = os.environ.get('WEBHOOK_METRICS_RETENTION', 3600)  # 1 hour
WEBHOOK_ERROR_THRESHOLD = os.environ.get('WEBHOOK_ERROR_THRESHOLD', 0.1)  # 10%
WEBHOOK_RESPONSE_TIME_THRESHOLD = os.environ.get('WEBHOOK_RESPONSE_TIME_THRESHOLD', 5.0)  # 5 seconds
WEBHOOK_ENABLE_CERT_PINNING = os.environ.get('WEBHOOK_ENABLE_CERT_PINNING', 'False').lower() == 'true'

# Webhook IP whitelist (comma-separated)
WEBHOOK_ALLOWED_IPS = [ip.strip() for ip in os.environ.get('WEBHOOK_ALLOWED_IPS', '').split(',') if ip.strip()]


# Cache configuration for webhook monitoring
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'default-cache',
        'TIMEOUT': 300,  # 5 minutes default
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
            'CULL_FREQUENCY': 3,
        }
    },
    'webhook_cache': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'webhook-cache',
        'TIMEOUT': 3600,  # 1 hour default
        'OPTIONS': {
            'MAX_ENTRIES': 10000,
            'CULL_FREQUENCY': 3,
        }
    }
}

# Development-specific webhook settings
if DEBUG:
    # More permissive settings for development
    WEBHOOK_RATE_LIMIT = 1000
    WEBHOOK_MAX_TIMESTAMP_AGE = 600  # 10 minutes
    WEBHOOK_ALLOWED_IPS = []  # Allow all IPs in development

# API Keys Configuration
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
APIFY_API_TOKEN = os.getenv('APIFY_API_TOKEN', '')
PINECONE_API_KEY = os.getenv('PINECONE_API_KEY', '')
BRIGHTDATA_API_KEY = os.getenv('BRIGHTDATA_API_KEY', '')
BRIGHTDATA_WEBHOOK_TOKEN = os.getenv('BRIGHTDATA_WEBHOOK_TOKEN', '')
