app = 'trackfutura'
primary_region = 'ord'

[build]

[env]
  DJANGO_SETTINGS_MODULE = "config.settings_fly"
  DEBUG = "False"
  DJANGO_SECURE_SSL_REDIRECT = "True"
  DJANGO_USE_TZ = "True"
  PYTHONPATH = "/app/backend"
  NODE_ENV = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  app = "python backend/manage.py runserver 0.0.0.0:8000"

[[statics]]
  guest_path = "/app/staticfiles"
  url_prefix = "/static/"

[[statics]]
  guest_path = "/app/frontend/dist"
  url_prefix = "/"