databases:
  - name: trackfutura-db
    databaseName: trackfutura
    user: trackfutura
    region: oregon

services:
  # Backend Django Service
  - type: web
    name: trackfutura-backend
    runtime: python
    repo: https://github.com/wina-futureobjects/track-futura-new.git
    branch: main
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2
    plan: starter
    region: oregon
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings_render
      - key: DEBUG
        value: False
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: True
      - key: DJANGO_SECURE_PROXY_SSL_HEADER
        value: HTTP_X_FORWARDED_PROTO,https
      - key: DJANGO_USE_TZ
        value: True
      - key: DD_TRACE_ENABLED
        value: false
      - key: DD_PROFILING_ENABLED
        value: false
      - key: DD_APM_ENABLED
        value: false
      - key: DD_LOGS_ENABLED
        value: false
      - key: DD_TRACE_STARTUP_LOGS
        value: false
      - key: DD_RUNTIME_METRICS_ENABLED
        value: false
      - key: DD_INSTRUMENTATION_TELEMETRY_ENABLED
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: trackfutura-db
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: BRIGHTDATA_WEBHOOK_BASE_URL
        value: https://trackfutura-backend.onrender.com
      - key: PORT
        value: 10000

  # Frontend React Service
  - type: web
    name: trackfutura-frontend
    runtime: node
    repo: https://github.com/wina-futureobjects/track-futura-new.git
    branch: main
    rootDir: frontend
    buildCommand: |
      npm ci
      npm run build
    startCommand: npx serve -s dist -l $PORT
    plan: starter
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://trackfutura-backend.onrender.com