applications:
  backend:
    source:
      root: "backend"
    type: "python:3.11"
    resources:
      profile_size: "XS"
    web:
      commands:
        start: "gunicorn config.wsgi --bind=unix:$SOCKET"
      upstream:
        socket_family: unix
      locations:
        "/":
          passthru: true
    build:
      flavor: none
    hooks:
      build: |
        pip install -r requirements.txt
        python manage.py collectstatic --noinput
      deploy: |
        python manage.py migrate
    variables:
      env:
        DJANGO_SETTINGS_MODULE: "config.settings"

  frontend:
    source:
      root: "frontend"
    type: "nodejs:18"
    resources:
      profile_size: "XS"
    web:
      commands:
        start: "npx serve -s dist"  # or `npm run preview` if using Vite
      upstream:
        socket_family: tcp
      locations:
        "/":
          passthru: true
    build:
      flavor: none
    hooks:
      build: |
        npm install
        npm run build

routes:
  "https://api.{default}/":
    type: upstream
    upstream: "backend:http"

  "https://{default}/":
    type: upstream
    upstream: "frontend:http"
