applications:
  backend:
    source:
      root: "backend"
    type: "python:3.11"
    disk: 8192 # 8 GB

    web:
      commands:
        start: "gunicorn config.wsgi --bind=unix:$SOCKET"
      upstream:
        socket_family: unix
      locations:
        "/":
          passthru: true
    build:
      flavor: none
    hooks:
      build: |
        pip install -r requirements.txt
        python manage.py collectstatic --noinput
      deploy: |
        python manage.py migrate
    relationships:
      database: "db:postgresql"
    variables:
      env:
        DJANGO_SETTINGS_MODULE: "config.settings"

  frontend:
    source:
      root: "frontend"
    type: "nodejs:18"
    web:
      commands:
        start: "npm run start"
      upstream:
        socket_family: tcp
      locations:
        "/":
          root: "dist"
          index:
            - "index.html"
          expires: -1
          scripts: false
          allow: true
        "/assets":
          root: "dist/assets"
          expires: 365d
          scripts: false
          allow: true
    build:
      flavor: none
    hooks:
      build: |
        npm install
        npm run build

# Define database service
services:
  db:
    type: postgresql:15
    configuration:
      extensions:
        - pg_trgm
        - unaccent

routes:
  "https://api.{default}/":
    type: upstream
    upstream: "backend:http"

  "https://{default}/":
    type: upstream
    upstream: "frontend:http"
    cache:
      enabled: true
      default_ttl: 0
      cookies: ['*']
