applications:
  backend:
    source:
      root: backend
    type: python:3.12
    size: S
    build:
      flavor: none
    dependencies:
      python3:
        pip: "24.0"
    hooks:
      build: |
        set -e
        echo "🚀 Starting TrackFutura build..."
        pip install --upgrade pip
        pip install -r requirements.txt
        export DJANGO_SETTINGS_MODULE=config.settings_upsun
        python manage.py collectstatic --noinput --clear
        python manage.py migrate --noinput
        echo "✅ Build complete!"
    web:
      commands:
        start: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
      locations:
        "/":
          passthru: true
        "/static":
          root: "staticfiles"
          expires: 86400
        "/media":
          root: "media"
          expires: 3600
    mounts:
      "media":
        source: "local"
        source_path: "media"
    variables:
      env:
        DJANGO_SETTINGS_MODULE: "config.settings_upsun"
        DEBUG: "False"
        PYTHONPATH: "/app/backend"
    relationships:
      database: "postgresql:postgresql"

services:
  postgresql:
    type: postgresql:15
    size: S
    disk: 1024

routes:
  "https://{default}/":
    type: upstream
    upstream: "backend:http"
  "https://www.{default}/":
    type: redirect
    to: "https://{default}/"