applications:
  backend:
    source:
      root: "backend"
    type: "python:3.11"

    web:
      commands:
        start: "waitress-serve --unix-socket=$SOCKET config.wsgi:application"
      upstream:
        socket_family: unix
      locations:
        "/":
          passthru: true
        "/static":
          allow: true
          expires: "1h"
          root: "staticfiles"
    build:
      flavor: none
    hooks:
      build: |
        set -eux
        # Upgrade pip first
        pip install --upgrade pip setuptools wheel
        # Install requirements with verbose output
        pip install -r requirements.txt --verbose
        # Basic Django check
        python -c "import django; print('Django installed successfully')"
      deploy: |
        set -eux
        # Collect static files (without whitenoise)
        python manage.py collectstatic --noinput --verbosity=2
        # Run migrations
        python manage.py migrate --verbosity=2
        # Test deployment configuration
        python manage.py test_deployment
    relationships:
      database: "db:postgresql"
    variables:
      env:
        DJANGO_SETTINGS_MODULE: "config.settings"
        DEBUG: "True"
        DJANGO_SECURE_SSL_REDIRECT: "False"
        # Completely disable DataDog tracing and monitoring
        DD_TRACE_ENABLED: "false"
        DD_PROFILING_ENABLED: "false"
        DD_APM_ENABLED: "false"
        DD_LOGS_ENABLED: "false"
        DD_TRACE_STARTUP_LOGS: "false"
        DD_RUNTIME_METRICS_ENABLED: "false"
        DD_INSTRUMENTATION_TELEMETRY_ENABLED: "false"
        PYTHONPATH: "/app"
    mounts:
      "/staticfiles":
        source: "local"
        source_path: "static_assets"

  frontend:
    source:
      root: "frontend"
    type: "nodejs:18"
    web:
      commands:
        start: "npm run start"
      upstream:
        socket_family: tcp
      locations:
        "/":
          root: "dist"
          index:
            - "index.html"
          expires: -1
          scripts: false
          allow: true
        "/assets":
          root: "dist/assets"
          expires: 365d
          scripts: false
          allow: true
    build:
      flavor: none
    hooks:
      build: |
        # Set API base URL for Upsun deployment
        # The API will be available at https://api.{default}/ based on our routes configuration
        export VITE_API_BASE_URL=""
        echo "Setting VITE_API_BASE_URL to empty string to use dynamic detection"
        echo "API will be detected as: https://api.\${hostname}"
        npm install
        npm run build

# Define database service
services:
  db:
    type: postgresql:15
    configuration:
      extensions:
        - pg_trgm
        - unaccent

routes:
  "https://api.{default}/":
    type: upstream
    upstream: "backend:http"

  "https://{default}/":
    type: upstream
    upstream: "frontend:http"
    cache:
      enabled: true
      default_ttl: 0
      cookies: ['*']
