# TrackFutura deployment with integrated React frontend - Force rebuild v3
applications:
  trackfutura:
    type: python:3.12
    
    dependencies:
      python3:
        pip: ">=23.0"
      nodejs:
        npm: "10"
    
    build:
      flavor: none
    
    web:
      commands:
        start: "cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    
    hooks:
      build: |
        set -e
        
        echo "=== BUILDING TRACKFUTURA FRONTEND + BACKEND ==="
        echo "Current directory: $(pwd)"
        echo "Listing files: $(ls -la)"
        
        echo "=== Step 1: Build React Frontend ==="
        cd frontend
        echo "Frontend directory contents: $(ls -la)"
        npm ci --production=false
        NODE_ENV=production npm run build
        echo "Frontend build completed, dist contents: $(ls -la dist/)"
        cd ..
        
        echo "=== Step 2: Install Python Dependencies ==="
        cd backend
        pip install -r requirements.txt
        cd ..
        
        echo "=== Step 3: Collect Django Static Files (includes frontend) ==="
        cd backend
        python manage.py collectstatic --noinput --clear
        echo "Static files collection completed: $(ls -la ../staticfiles/)"
        
        echo "=== BUILD COMPLETED SUCCESSFULLY ==="
      
      deploy: |
        cd backend
        python manage.py migrate --noinput
        echo "🚀 Deploying BrightData snapshots to production..."
        python ../direct_production_deploy.py
    
    relationships:
      database: postgresql:postgresql

services:
  postgresql:
    type: postgresql:15

routes:
  "https://{default}/":
    type: upstream
    upstream: "trackfutura:http"
