applications:
  trackfutura:
    source:
      root: backend
    type: python:3.12
    
    dependencies:
      python3:
        pip: ">=23.0"
    
    build:
      flavor: none
    
    web:
      commands:
        start: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    
    hooks:
      build: |
        pip install -r requirements.txt
        python manage.py collectstatic --noinput
      
      deploy: |
        python manage.py migrate --noinput
    
    disk: 1024

services:
  postgresql:
    type: postgresql:15
    disk: 512

routes:
  "https://{default}/":
    type: upstream
    upstream: "trackfutura:http"