# Generated by Django 5.2 on 2025-09-29 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('user_posted', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('num_comments', models.IntegerField(default=0)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('photos', models.TextField(blank=True, null=True)),
                ('videos', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_comments', models.TextField(blank=True, null=True)),
                ('post_id', models.CharField(max_length=100)),
                ('discovery_input', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.URLField(blank=True, max_length=500, null=True)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('platform_type', models.CharField(blank=True, max_length=50, null=True)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('tagged_users', models.TextField(blank=True, null=True)),
                ('followers', models.IntegerField(blank=True, null=True)),
                ('posts_count', models.IntegerField(blank=True, null=True)),
                ('profile_image_link', models.URLField(blank=True, max_length=500, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_paid_partnership', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TikTok Post',
                'verbose_name_plural': 'TikTok Posts',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('posts', 'Posts'), ('reels', 'Reels'), ('comments', 'Comments')], default='posts', help_text='Type of content stored in this folder', max_length=20)),
                ('folder_type', models.CharField(choices=[('run', 'Scraping Run'), ('service', 'Platform Service'), ('content', 'Content Folder')], default='content', help_text='Type of folder in the hierarchy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_folder', models.ForeignKey(blank=True, help_text='Parent folder in the hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='tiktok_data.folder')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_folders', to='users.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
