# Generated by Django 5.2 on 2025-09-29 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiktok_data', '0001_initial'),
        ('track_accounts', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='scraping_run',
            field=models.ForeignKey(blank=True, help_text='Associated scraping run', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_folders', to='workflow.scrapingrun'),
        ),
        migrations.AddField(
            model_name='folder',
            name='unified_job_folder',
            field=models.ForeignKey(blank=True, help_text='Linked unified job folder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiktok_platform_folders', to='track_accounts.unifiedrunfolder'),
        ),
        migrations.AddField(
            model_name='tiktokpost',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tiktok_data.folder'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['unified_job_folder'], name='tiktok_data_unified_45e788_idx'),
        ),
        migrations.AddIndex(
            model_name='tiktokpost',
            index=models.Index(fields=['user_posted'], name='tiktok_data_user_po_c08b58_idx'),
        ),
        migrations.AddIndex(
            model_name='tiktokpost',
            index=models.Index(fields=['post_id'], name='tiktok_data_post_id_a42552_idx'),
        ),
        migrations.AddIndex(
            model_name='tiktokpost',
            index=models.Index(fields=['date_posted'], name='tiktok_data_date_po_856caa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tiktokpost',
            unique_together={('post_id', 'folder')},
        ),
    ]
