# Generated by Django 5.2 on 2025-08-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_data', '0006_alter_folder_folder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_type',
            field=models.CharField(choices=[('run', 'Scraping Run'), ('service', 'Platform Service'), ('content', 'Content Folder')], default='content', help_text='Type of folder in the hierarchy', max_length=20),
        ),
    ]
