# Generated by Django 5.2 on 2025-08-10 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0022_scraperrequest_batch_run_and_more'),
        ('tiktok_data', '0008_folder_unified_job_folder_and_more'),
        ('track_accounts', '0020_remove_tracksource_brightdata_config_and_more'),
        ('users', '0006_service_platform_platformservice'),
        ('workflow', '0010_remove_scrapingjob_workflow_sc_request_1a8087_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='scrape_job',
            field=models.ForeignKey(blank=True, help_text='Direct link to scraping job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_folders', to='workflow.scrapingjob'),
        ),
        migrations.AddField(
            model_name='tiktokpost',
            name='scrape_job',
            field=models.ForeignKey(blank=True, help_text='Direct link to scraping job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_posts', to='workflow.scrapingjob'),
        ),
        migrations.AddField(
            model_name='tiktokpost',
            name='scraper_request',
            field=models.ForeignKey(blank=True, help_text='Direct link to scraper request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_posts', to='brightdata_integration.scraperrequest'),
        ),
        migrations.AddField(
            model_name='tiktokpost',
            name='webhook_received_at',
            field=models.DateTimeField(blank=True, help_text='When webhook was received', null=True),
        ),
        migrations.AddField(
            model_name='tiktokpost',
            name='webhook_snapshot_id',
            field=models.CharField(blank=True, help_text='Snapshot ID from webhook', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='category',
            field=models.CharField(choices=[('posts', 'Posts'), ('comments', 'Comments')], default='posts', max_length=20),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['scrape_job'], name='tiktok_data_scrape__71a579_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['scraping_run'], name='tiktok_data_scrapin_6cc62f_idx'),
        ),
        migrations.AddIndex(
            model_name='tiktokpost',
            index=models.Index(fields=['scrape_job'], name='tiktok_data_scrape__f73a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='tiktokpost',
            index=models.Index(fields=['scraper_request'], name='tiktok_data_scraper_9c9d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='tiktokpost',
            index=models.Index(fields=['webhook_snapshot_id'], name='tiktok_data_webhook_23687b_idx'),
        ),
    ]
