# Generated by Django 5.2 on 2025-08-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_data', '0010_tiktokpost_job_folder_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='folder',
            name='tiktok_data_scrape__71a579_idx',
        ),
        migrations.RemoveIndex(
            model_name='folder',
            name='tiktok_data_scrapin_6cc62f_idx',
        ),
        migrations.RemoveIndex(
            model_name='tiktokpost',
            name='tiktok_data_scrape__f73a7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='tiktokpost',
            name='tiktok_data_scraper_9c9d6c_idx',
        ),
        migrations.RemoveIndex(
            model_name='tiktokpost',
            name='tiktok_data_webhook_23687b_idx',
        ),
        migrations.RemoveIndex(
            model_name='tiktokpost',
            name='tiktok_data_job_fol_cda94c_idx',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='scrape_job',
        ),
        migrations.RemoveField(
            model_name='tiktokpost',
            name='job_folder',
        ),
        migrations.RemoveField(
            model_name='tiktokpost',
            name='scrape_job',
        ),
        migrations.RemoveField(
            model_name='tiktokpost',
            name='scraper_request',
        ),
        migrations.RemoveField(
            model_name='tiktokpost',
            name='webhook_received_at',
        ),
        migrations.RemoveField(
            model_name='tiktokpost',
            name='webhook_snapshot_id',
        ),
        migrations.AlterField(
            model_name='folder',
            name='category',
            field=models.CharField(choices=[('posts', 'Posts'), ('reels', 'Reels'), ('comments', 'Comments')], default='posts', help_text='Type of content stored in this folder', max_length=20),
        ),
    ]
