# Generated by Django 5.2 on 2025-10-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightdatascraperrequest',
            name='response_data',
            field=models.JSONField(blank=True, help_text='BrightData response data', null=True),
        ),
    ]
