# Generated by Django 5.1.6 on 2025-05-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brightdata_integration", "0002_brightdataconfig_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchscraperjob",
            name="source_folder_ids",
            field=models.JSONField(
                help_text="List of project IDs to scrape from (folders have been removed)"
            ),
        ),
    ]
