# Generated by Django 5.2 on 2025-10-08 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0002_brightdatascraperrequest_response_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightdatascraperrequest',
            name='folder_id',
            field=models.IntegerField(blank=True, help_text='Associated job folder ID', null=True),
        ),
        migrations.AddField(
            model_name='brightdatascraperrequest',
            name='user_id',
            field=models.IntegerField(blank=True, help_text='User who triggered the job', null=True),
        ),
        migrations.AlterField(
            model_name='brightdatascraperrequest',
            name='batch_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_requests', to='brightdata_integration.brightdatabatchjob'),
        ),
        migrations.AlterField(
            model_name='brightdatascraperrequest',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_requests', to='brightdata_integration.brightdataconfig'),
        ),
        migrations.AlterField(
            model_name='brightdatascraperrequest',
            name='content_type',
            field=models.CharField(default='posts', max_length=50),
        ),
        migrations.AlterField(
            model_name='brightdatascraperrequest',
            name='source_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='brightdatascraperrequest',
            name='target_url',
            field=models.CharField(max_length=500),
        ),
    ]
