# Generated by Django 5.2 on 2025-05-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0003_alter_batchscraperjob_source_folder_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brightdataconfig',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('facebook_comments', 'Facebook Comments'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn')], default='facebook', max_length=20),
        ),
    ]
