# Generated by Django 5.2 on 2025-10-11 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0004_brightdatascrapedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brightdatascrapedpost',
            name='scraper_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraped_posts', to='brightdata_integration.brightdatascraperrequest'),
        ),
    ]
