# Generated by Django 5.2 on 2025-10-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0005_add_scrape_number'),
        ('brightdata_integration', '0005_alter_brightdatascrapedpost_scraper_request'),
    ]

    operations = [
    ]
