# Generated by Django 5.2 on 2025-05-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0005_alter_brightdataconfig_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brightdataconfig',
            name='platform',
            field=models.CharField(choices=[('facebook_posts', 'Facebook Posts'), ('facebook_reels', 'Facebook Reels'), ('facebook_comments', 'Facebook Comments'), ('instagram_posts', 'Instagram Posts'), ('instagram_reels', 'Instagram Reels'), ('instagram_comments', 'Instagram Comments'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn')], default='facebook_posts', max_length=30),
        ),
        migrations.AlterField(
            model_name='scraperrequest',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('reel', 'Reel'), ('profile', 'Profile'), ('comment', 'Comment')], default='post', max_length=20),
        ),
        migrations.AlterField(
            model_name='scraperrequest',
            name='platform',
            field=models.CharField(choices=[('facebook_posts', 'Facebook Posts'), ('facebook_reels', 'Facebook Reels'), ('facebook_comments', 'Facebook Comments'), ('instagram_posts', 'Instagram Posts'), ('instagram_reels', 'Instagram Reels'), ('instagram_comments', 'Instagram Comments'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn')], max_length=30),
        ),
    ]
