# Generated by Django 5.2 on 2025-10-12 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0002_add_folder_relationship'),
        ('brightdata_integration', '0006_merge_20251012_1141'),
    ]

    operations = [
    ]
