# Generated by Django 5.2 on 2025-05-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0006_alter_brightdataconfig_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchscraperjob',
            name='content_types_to_scrape',
            field=models.JSONField(default=dict, help_text="Dictionary mapping platforms to content types: {'facebook': ['post', 'reel'], 'instagram': ['post', 'comment']}"),
        ),
        migrations.AlterField(
            model_name='batchscraperjob',
            name='output_folder_pattern',
            field=models.CharField(default='{platform}_{content_type}_{date}_{job_name}', help_text='Pattern for auto-created folder names', max_length=255),
        ),
    ]
