# Generated by Django 5.2 on 2025-05-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0007_batchscraperjob_content_types_to_scrape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchscraperjob',
            name='processed_sources',
            field=models.IntegerField(default=0, help_text='Number of sources processed so far'),
        ),
        migrations.AddField(
            model_name='batchscraperjob',
            name='total_sources',
            field=models.IntegerField(default=0, help_text='Total number of sources to process'),
        ),
        migrations.AddField(
            model_name='scraperrequest',
            name='source_name',
            field=models.CharField(blank=True, help_text='Name of the tracked source', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchscraperjob',
            name='processed_accounts',
            field=models.IntegerField(default=0, help_text='Legacy field - use processed_sources instead'),
        ),
        migrations.AlterField(
            model_name='batchscraperjob',
            name='total_accounts',
            field=models.IntegerField(default=0, help_text='Legacy field - use total_sources instead'),
        ),
        migrations.AlterField(
            model_name='scraperrequest',
            name='account_name',
            field=models.CharField(blank=True, help_text='Legacy field - use source_name instead', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scraperrequest',
            name='iac_no',
            field=models.CharField(blank=True, help_text='IAC number of the tracked source', max_length=100, null=True),
        ),
    ]
