# Generated by Django 5.2 on 2025-10-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0007_merge_20251012_1259'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brightdatascraperrequest',
            name='bd_run_folder_scrape_idx',
        ),
        migrations.RenameIndex(
            model_name='brightdatascraperrequest',
            new_name='brightdata__folder__180c90_idx',
            old_name='brightdata__folder__scrape_idx',
        ),
        migrations.RemoveField(
            model_name='brightdatascraperrequest',
            name='run_folder',
        ),
        migrations.AddField(
            model_name='brightdatascrapedpost',
            name='webhook_delivered',
            field=models.BooleanField(default=False, help_text='True if delivered via BrightData webhook, False if fetched via polling'),
        ),
    ]
