# Generated by Django 5.2 on 2025-10-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0008_remove_brightdatascraperrequest_bd_run_folder_scrape_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightdatawebhookevent',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brightdatawebhookevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('processed', 'Processed'), ('failed', 'Failed'), ('json_error', 'JSON Error'), ('test_webhook', 'Test Webhook'), ('test_processed', 'Test Processed'), ('file_url_error', 'File URL Error'), ('processing_error', 'Processing Error'), ('error', 'Error')], default='pending', max_length=50),
        ),
    ]
