# Generated by Django 5.2 on 2025-06-10 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0011_remove_iac_no_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrightdataNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.CharField(help_text='BrightData snapshot/request ID', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('processing', 'Processing'), ('completed', 'Completed'), ('finished', 'Finished'), ('failed', 'Failed'), ('error', 'Error'), ('cancelled', 'Cancelled')], max_length=20)),
                ('message', models.TextField(blank=True, help_text='Notification message from BrightData', null=True)),
                ('raw_data', models.JSONField(help_text='Raw notification data from BrightData')),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('scraper_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='brightdata_integration.scraperrequest')),
            ],
            options={
                'verbose_name': 'BrightData Notification',
                'verbose_name_plural': 'BrightData Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
