# Generated by Django 5.2 on 2025-07-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0012_brightdatanotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchscraperjob',
            name='platform_params',
            field=models.JSONField(blank=True, help_text='Platform-specific parameters for scraping', null=True),
        ),
    ]
