# Generated by Django 5.2 on 2025-08-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0013_add_platform_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brightdataconfig',
            name='platform',
            field=models.CharField(choices=[('facebook_posts', 'Facebook Posts'), ('facebook_reels', 'Facebook Reels'), ('facebook_comments', 'Facebook Comments'), ('instagram_posts', 'Instagram Posts'), ('instagram_reels', 'Instagram Reels'), ('instagram_comments', 'Instagram Comments'), ('tiktok_posts', 'TikTok Posts'), ('tiktok', 'TikTok'), ('linkedin_posts', 'LinkedIn Posts'), ('linkedin', 'LinkedIn')], default='facebook_posts', max_length=30),
        ),
    ]
