# Generated by Django 5.2 on 2025-08-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0014_alter_brightdataconfig_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchscraperjob',
            name='num_of_posts',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
