# Generated by Django 5.2 on 2025-08-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0015_alter_batchscraperjob_num_of_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperrequest',
            name='num_of_posts',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
