# Generated by Django 5.2 on 2025-08-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0016_alter_scraperrequest_num_of_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], max_length=20)),
                ('snapshot_id', models.CharField(max_length=255)),
                ('raw_payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webhook_events',
                'indexes': [models.Index(fields=['status', 'received_at'], name='webhook_eve_status_f769dd_idx'), models.Index(fields=['snapshot_id'], name='webhook_eve_snapsho_1dbab5_idx'), models.Index(fields=['platform'], name='webhook_eve_platfor_7c529e_idx')],
            },
        ),
    ]
