# Generated by Django 5.2 on 2025-08-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0017_webhookevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookevent',
            name='snapshot_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
