# Generated by Django 5.2 on 2025-08-09 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0018_alter_webhookevent_snapshot_id'),
        ('users', '0006_service_platform_platformservice'),
        ('workflow', '0007_scheduledscrapingtask_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_data', models.JSONField(help_text='Normalized data extracted from raw_payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scrape Output',
                'verbose_name_plural': 'Scrape Outputs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='brightdataconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='brightdataconfig',
            name='api_key',
            field=models.CharField(blank=True, help_text='Preferred API key field; use instead of api_token', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brightdataconfig',
            name='notify_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='brightdataconfig',
            name='platform_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brightdata_configs', to='users.platformservice'),
        ),
        migrations.AddField(
            model_name='brightdataconfig',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='brightdatanotification',
            name='delivery_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brightdatanotification',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_webhook_events', to='workflow.scrapingjob'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_webhook_events', to='workflow.scrapingjob'),
        ),
        migrations.AddConstraint(
            model_name='brightdataconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('platform', 'is_active'), name='uq_active_config_per_legacy_platform'),
        ),
        migrations.AddConstraint(
            model_name='brightdataconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('platform_service', 'is_active'), name='uq_active_config_per_platform_service'),
        ),
        migrations.AddField(
            model_name='scrapeoutput',
            name='data_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='brightdata_integration.webhookevent'),
        ),
    ]
