# Generated by Django 5.2 on 2025-08-09 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0019_scrapeoutput_alter_brightdataconfig_unique_together_and_more'),
        ('track_accounts', '0019_tracksource_brightdata_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperrequest',
            name='track_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraper_requests', to='track_accounts.tracksource'),
        ),
    ]
