# Generated by Django 5.2 on 2025-08-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0020_scraperrequest_track_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeoutput',
            name='data_event',
        ),
        migrations.RemoveConstraint(
            model_name='brightdataconfig',
            name='uq_active_config_per_legacy_platform',
        ),
        migrations.RemoveConstraint(
            model_name='brightdataconfig',
            name='uq_active_config_per_platform_service',
        ),
        migrations.AlterUniqueTogether(
            name='brightdataconfig',
            unique_together={('platform', 'is_active')},
        ),
        migrations.RemoveField(
            model_name='brightdatanotification',
            name='delivery_id',
        ),
        migrations.RemoveField(
            model_name='brightdatanotification',
            name='job',
        ),
        migrations.RemoveField(
            model_name='scraperrequest',
            name='track_source',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='job',
        ),
        migrations.DeleteModel(
            name='ScrapeOutput',
        ),
        migrations.RemoveField(
            model_name='brightdataconfig',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='brightdataconfig',
            name='notify_url',
        ),
        migrations.RemoveField(
            model_name='brightdataconfig',
            name='platform_service',
        ),
        migrations.RemoveField(
            model_name='brightdataconfig',
            name='webhook_url',
        ),
    ]
