# Generated by Django 5.2 on 2025-08-10 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0021_remove_scrapeoutput_data_event_and_more'),
        ('workflow', '0009_remove_scrapingjob_track_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperrequest',
            name='batch_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_requests', to='workflow.scrapingrun'),
        ),
        migrations.AddField(
            model_name='scraperrequest',
            name='data_webhook_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scraperrequest',
            name='notify_webhook_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scraperrequest',
            name='scrape_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_requests', to='workflow.scrapingjob'),
        ),
        migrations.AddField(
            model_name='scraperrequest',
            name='webhook_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraperrequest',
            name='webhook_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
