# Generated by Django 5.2 on 2025-08-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0022_scraperrequest_batch_run_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperrequest',
            name='batch_run',
        ),
        migrations.RemoveField(
            model_name='scraperrequest',
            name='data_webhook_id',
        ),
        migrations.RemoveField(
            model_name='scraperrequest',
            name='notify_webhook_id',
        ),
        migrations.RemoveField(
            model_name='scraperrequest',
            name='scrape_job',
        ),
        migrations.RemoveField(
            model_name='scraperrequest',
            name='webhook_received_at',
        ),
        migrations.RemoveField(
            model_name='scraperrequest',
            name='webhook_status',
        ),
    ]
