# Generated by Django 5.2 on 2025-09-29 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApifyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('platform', models.CharField(choices=[('facebook_posts', 'Facebook Posts'), ('facebook_reels', 'Facebook Reels'), ('facebook_comments', 'Facebook Comments'), ('instagram_posts', 'Instagram Posts'), ('instagram_reels', 'Instagram Reels'), ('instagram_comments', 'Instagram Comments'), ('tiktok_posts', 'TikTok Posts'), ('linkedin_posts', 'LinkedIn Posts')], max_length=30, unique=True)),
                ('api_token', models.CharField(max_length=255)),
                ('actor_id', models.CharField(help_text='Apify Actor ID for this platform', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apify Configuration',
                'verbose_name_plural': 'Apify Configurations',
            },
        ),
        migrations.CreateModel(
            name='ApifyWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('run_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('raw_data', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Apify Webhook Event',
                'verbose_name_plural': 'Apify Webhook Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApifyBatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_folder_ids', models.JSONField(blank=True, default=list)),
                ('platforms_to_scrape', models.JSONField(default=list)),
                ('content_types_to_scrape', models.JSONField(default=dict)),
                ('num_of_posts', models.IntegerField(default=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('auto_create_folders', models.BooleanField(default=True)),
                ('output_folder_pattern', models.CharField(default='platform/service/date', max_length=200)),
                ('platform_params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_sources', models.IntegerField(default=0)),
                ('processed_sources', models.IntegerField(default=0)),
                ('successful_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('job_metadata', models.JSONField(blank=True, default=dict)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apify_batch_jobs', to='users.project')),
            ],
            options={
                'verbose_name': 'Apify Batch Job',
                'verbose_name_plural': 'Apify Batch Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApifyScraperRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('content_type', models.CharField(max_length=50)),
                ('target_url', models.URLField()),
                ('source_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraper_requests', to='apify_integration.apifybatchjob')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraper_requests', to='apify_integration.apifyconfig')),
            ],
            options={
                'verbose_name': 'Apify Scraper Request',
                'verbose_name_plural': 'Apify Scraper Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApifyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('raw_data', models.JSONField(default=dict)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_headers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scraper_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apify_integration.apifyscraperrequest')),
            ],
            options={
                'verbose_name': 'Apify Notification',
                'verbose_name_plural': 'Apify Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
