# Generated by Django 5.1.6 on 2025-04-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstagramPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("user_posted", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("hashtags", models.TextField(blank=True, null=True)),
                ("num_comments", models.IntegerField(default=0)),
                ("date_posted", models.DateTimeField()),
                ("likes", models.IntegerField(default=0)),
                ("photos", models.TextField(blank=True, null=True)),
                ("videos", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("latest_comments", models.TextField(blank=True, null=True)),
                ("post_id", models.CharField(max_length=255)),
                ("discovery_input", models.TextField(blank=True, null=True)),
                ("thumbnail", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "engagement_score",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("tagged_users", models.TextField(blank=True, null=True)),
                ("followers", models.IntegerField(blank=True, default=0, null=True)),
                ("posts_count", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "profile_image_link",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_paid_partnership", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Instagram Post",
                "verbose_name_plural": "Instagram Posts",
                "ordering": ["-date_posted"],
                "indexes": [
                    models.Index(
                        fields=["user_posted"], name="instagram_d_user_po_974d1e_idx"
                    ),
                    models.Index(
                        fields=["post_id"], name="instagram_d_post_id_3540ae_idx"
                    ),
                    models.Index(
                        fields=["date_posted"], name="instagram_d_date_po_c7b989_idx"
                    ),
                ],
            },
        ),
    ]
