# Generated by Django 5.2 on 2025-09-29 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instagram_data', '0001_initial'),
        ('track_accounts', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='scraping_run',
            field=models.ForeignKey(blank=True, help_text='Associated scraping run', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_folders', to='workflow.scrapingrun'),
        ),
        migrations.AddField(
            model_name='folder',
            name='unified_job_folder',
            field=models.ForeignKey(blank=True, help_text='Linked unified job folder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_platform_folders', to='track_accounts.unifiedrunfolder'),
        ),
        migrations.AddField(
            model_name='commentscrapingjob',
            name='result_folder',
            field=models.ForeignKey(blank=True, help_text='Folder to store scraped comments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_scraping_jobs', to='instagram_data.folder'),
        ),
        migrations.AddField(
            model_name='instagramcomment',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instagram_data.folder'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='instagram_data.folder'),
        ),
        migrations.AddField(
            model_name='instagramcomment',
            name='instagram_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instagram_data.instagrampost'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['unified_job_folder'], name='instagram_d_unified_7fa8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['user_posted'], name='instagram_d_user_po_974d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['post_id'], name='instagram_d_post_id_3540ae_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['date_posted'], name='instagram_d_date_po_c7b989_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['content_type'], name='instagram_d_content_992ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['product_type'], name='instagram_d_product_eb9123_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instagrampost',
            unique_together={('post_id', 'folder')},
        ),
        migrations.AddIndex(
            model_name='instagramcomment',
            index=models.Index(fields=['comment_user'], name='instagram_d_comment_15e942_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramcomment',
            index=models.Index(fields=['comment_id'], name='instagram_d_comment_b0d9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramcomment',
            index=models.Index(fields=['post_id'], name='instagram_d_post_id_ba97d3_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramcomment',
            index=models.Index(fields=['comment_date'], name='instagram_d_comment_644415_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instagramcomment',
            unique_together={('comment_id', 'folder')},
        ),
    ]
