# Generated by Django 5.1.6 on 2025-04-24 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="instagrampost",
            name="date_posted",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instagrampost",
            name="discovery_input",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="instagrampost",
            name="engagement_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="instagrampost",
            name="followers",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instagrampost",
            name="post_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="instagrampost",
            name="posts_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instagrampost",
            name="user_posted",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="instagrampost",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="instagram_data.folder",
            ),
        ),
    ]
