# Generated by Django 5.1.6 on 2025-04-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_data", "0002_folder_alter_instagrampost_date_posted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instagrampost",
            name="post_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="instagrampost",
            unique_together={("post_id", "folder")},
        ),
    ]
