# Generated by Django 5.1.6 on 2025-04-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_data", "0003_alter_instagrampost_post_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instagrampost",
            name="platform_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
