# Generated by Django 5.1.6 on 2025-05-13 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram_data", "0004_instagrampost_platform_type"),
        ("users", "0002_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instagram_folders",
                to="users.project",
            ),
        ),
    ]
