# Generated by Django 5.2 on 2025-05-28 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_data', '0005_folder_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='category',
            field=models.CharField(choices=[('posts', 'Posts'), ('comments', 'Comments')], default='posts', max_length=20),
        ),
        migrations.CreateModel(
            name='InstagramComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=255)),
                ('post_id', models.CharField(max_length=255)),
                ('post_url', models.URLField(max_length=500)),
                ('post_user', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField()),
                ('comment_date', models.DateTimeField(blank=True, null=True)),
                ('comment_user', models.CharField(max_length=255)),
                ('comment_user_url', models.URLField(blank=True, max_length=500, null=True)),
                ('likes_number', models.IntegerField(default=0)),
                ('replies_number', models.IntegerField(default=0)),
                ('replies', models.JSONField(blank=True, null=True)),
                ('hashtag_comment', models.TextField(blank=True, null=True)),
                ('tagged_users_in_comment', models.JSONField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instagram_data.folder')),
                ('instagram_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instagram_data.instagrampost')),
            ],
            options={
                'verbose_name': 'Instagram Comment',
                'verbose_name_plural': 'Instagram Comments',
                'ordering': ['-comment_date'],
                'indexes': [models.Index(fields=['comment_user'], name='instagram_d_comment_15e942_idx'), models.Index(fields=['comment_id'], name='instagram_d_comment_b0d9ed_idx'), models.Index(fields=['post_id'], name='instagram_d_post_id_ba97d3_idx'), models.Index(fields=['comment_date'], name='instagram_d_comment_644415_idx')],
                'unique_together': {('comment_id', 'folder')},
            },
        ),
    ]
