# Generated by Django 5.2 on 2025-05-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_data', '0006_folder_category_instagramcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='category',
            field=models.CharField(choices=[('posts', 'Posts'), ('reels', 'Reels'), ('comments', 'Comments')], default='posts', max_length=20),
        ),
    ]
