# Generated by Django 5.2 on 2025-05-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_data', '0007_alter_folder_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='alt_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='audio',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='audio_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='coauthor_producers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='content_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='engagement_score_view',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='following',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='has_handshake',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='instagram_pk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='length',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='partnership_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='photos_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='post_content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='profile_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='shortcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='top_comments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='user_posted_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='user_profile_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='video_play_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='video_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='video_view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='videos_duration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='hashtags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='latest_comments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='photos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='tagged_users',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='videos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['content_type'], name='instagram_d_content_992ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['product_type'], name='instagram_d_product_eb9123_idx'),
        ),
    ]
