# Generated by Django 5.2 on 2025-08-10 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0022_scraperrequest_batch_run_and_more'),
        ('instagram_data', '0014_folder_unified_job_folder_and_more'),
        ('track_accounts', '0020_remove_tracksource_brightdata_config_and_more'),
        ('users', '0006_service_platform_platformservice'),
        ('workflow', '0010_remove_scrapingjob_workflow_sc_request_1a8087_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='scrape_job',
            field=models.ForeignKey(blank=True, help_text='Direct link to scraping job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_folders', to='workflow.scrapingjob'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='scrape_job',
            field=models.ForeignKey(blank=True, help_text='Direct link to scraping job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_posts', to='workflow.scrapingjob'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='scraper_request',
            field=models.ForeignKey(blank=True, help_text='Direct link to scraper request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_posts', to='brightdata_integration.scraperrequest'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='webhook_received_at',
            field=models.DateTimeField(blank=True, help_text='When webhook was received', null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='webhook_snapshot_id',
            field=models.CharField(blank=True, help_text='Snapshot ID from webhook', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['scrape_job'], name='instagram_d_scrape__ef58af_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['scraping_run'], name='instagram_d_scrapin_7dcfdc_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['scrape_job'], name='instagram_d_scrape__5ac7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['scraper_request'], name='instagram_d_scraper_4c9573_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['webhook_snapshot_id'], name='instagram_d_webhook_4b3193_idx'),
        ),
    ]
