# Generated by Django 5.2 on 2025-08-10 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0022_scraperrequest_batch_run_and_more'),
        ('instagram_data', '0015_folder_scrape_job_instagrampost_scrape_job_and_more'),
        ('track_accounts', '0020_remove_tracksource_brightdata_config_and_more'),
        ('workflow', '0010_remove_scrapingjob_workflow_sc_request_1a8087_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='job_folder',
            field=models.ForeignKey(blank=True, help_text='Direct link to job folder for webhook routing', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_posts', to='track_accounts.unifiedrunfolder'),
        ),
        migrations.AddIndex(
            model_name='instagrampost',
            index=models.Index(fields=['job_folder'], name='instagram_d_job_fol_704832_idx'),
        ),
    ]
