# Generated by Django 5.2 on 2025-08-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_data', '0016_instagrampost_job_folder_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='folder',
            name='instagram_d_scrape__ef58af_idx',
        ),
        migrations.RemoveIndex(
            model_name='folder',
            name='instagram_d_scrapin_7dcfdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='instagrampost',
            name='instagram_d_scrape__5ac7d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='instagrampost',
            name='instagram_d_scraper_4c9573_idx',
        ),
        migrations.RemoveIndex(
            model_name='instagrampost',
            name='instagram_d_webhook_4b3193_idx',
        ),
        migrations.RemoveIndex(
            model_name='instagrampost',
            name='instagram_d_job_fol_704832_idx',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='scrape_job',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='job_folder',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='scrape_job',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='scraper_request',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='webhook_received_at',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='webhook_snapshot_id',
        ),
    ]
