# Generated by Django 5.2 on 2025-08-03 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brightdata_integration', '0013_add_platform_params'),
        ('users', '0006_service_platform_platformservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.JSONField(help_text='List of URLs for scraping')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_input_collections', to=settings.AUTH_USER_MODEL)),
                ('platform_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_collections', to='users.platformservice')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_collections', to='users.project')),
            ],
            options={
                'verbose_name': 'Input Collection',
                'verbose_name_plural': 'Input Collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_tasks', to='brightdata_integration.batchscraperjob')),
                ('input_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_tasks', to='workflow.inputcollection')),
            ],
            options={
                'verbose_name': 'Workflow Task',
                'verbose_name_plural': 'Workflow Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
