# Generated by Django

from django.db import migrations


def clear_existing_data(apps, schema_editor):
    """Clear existing workflow data to prepare for Apify to BrightData migration"""
    ScrapingJob = apps.get_model('workflow', 'ScrapingJob')
    WorkflowTask = apps.get_model('workflow', 'WorkflowTask')
    ScheduledScrapingTask = apps.get_model('workflow', 'ScheduledScrapingTask')
    
    # Clear all existing data
    ScrapingJob.objects.all().delete()
    WorkflowTask.objects.all().delete()
    ScheduledScrapingTask.objects.all().delete()


def reverse_clear_data(apps, schema_editor):
    """Reverse operation - no data to restore"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
        ('brightdata_integration', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_existing_data, reverse_clear_data),
    ]