# Generated by Django 5.2 on 2025-08-04 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_accounts', '0012_alter_tracksource_service_name_and_more'),
        ('users', '0006_service_platform_platformservice'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputcollection',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='workflowtask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='inputcollection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inputcollection',
            name='urls',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='ScheduledScrapingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], max_length=50)),
                ('service_type', models.CharField(choices=[('posts', 'Posts'), ('comments', 'Comments'), ('reels', 'Reels'), ('profiles', 'Profiles')], default='posts', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom Interval')], default='daily', max_length=20)),
                ('schedule_interval', models.IntegerField(default=1, help_text='Interval in hours for custom schedule')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('num_of_posts', models.IntegerField(default=10)),
                ('auto_create_folders', models.BooleanField(default=True)),
                ('brightdata_dataset_id', models.CharField(default='gd_lk5ns7kz21pck8jpis', max_length=100)),
                ('brightdata_api_key', models.CharField(default='c20a28d5-5c6c-43c3-9567-a6d7c193e727', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error')], default='active', max_length=20)),
                ('total_runs', models.IntegerField(default=0)),
                ('successful_runs', models.IntegerField(default=0)),
                ('failed_runs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='users.project')),
                ('track_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='track_accounts.tracksource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
