# Generated by Django 5.2 on 2025-10-07 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0001_initial'),
        ('workflow', '0002_clear_data_for_brightdata_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledscrapingtask',
            name='apify_actor_id',
        ),
        migrations.RemoveField(
            model_name='scheduledscrapingtask',
            name='apify_api_token',
        ),
        migrations.AddField(
            model_name='scheduledscrapingtask',
            name='brightdata_api_token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scheduledscrapingtask',
            name='brightdata_dataset_id',
            field=models.CharField(default='default_dataset_id', max_length=100),
        ),
        migrations.AlterField(
            model_name='scrapingjob',
            name='batch_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_jobs', to='brightdata_integration.brightdatabatchjob'),
        ),
        migrations.AlterField(
            model_name='scrapingjob',
            name='request_id',
            field=models.CharField(blank=True, help_text='BrightData request ID for tracking', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workflowtask',
            name='batch_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_tasks', to='brightdata_integration.brightdatabatchjob'),
        ),
    ]
