# Generated by Django 5.2 on 2025-08-05 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_scrapingrun_scrapingjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingjob',
            name='input_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraping_jobs', to='workflow.inputcollection'),
        ),
    ]
