# Generated by Django 5.2 on 2025-08-06 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0014_alter_brightdataconfig_platform'),
        ('workflow', '0004_alter_scrapingjob_input_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingRunFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Folder name, e.g., 'Scraping Run - 2024-01-15 14:30'", max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scraping_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='workflow.scrapingrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformServiceFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='Platform name (facebook, instagram, etc.)', max_length=50)),
                ('service_type', models.CharField(help_text='Service type (posts, comments, etc.)', max_length=50)),
                ('name', models.CharField(help_text="Folder name, e.g., 'Facebook - Posts'", max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_urls', models.JSONField(default=list, help_text='List of URLs processed in this folder')),
                ('configuration', models.JSONField(default=dict, help_text='Configuration used for this platform-service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_folders', to='brightdata_integration.batchscraperjob')),
                ('scraping_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_folders', to='workflow.scrapingjob')),
                ('scraping_run_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_folders', to='workflow.scrapingrunfolder')),
            ],
            options={
                'ordering': ['platform', 'service_type'],
                'unique_together': {('scraping_run_folder', 'platform', 'service_type')},
            },
        ),
    ]
