# Generated by Django 5.2 on 2025-08-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_scrapingrunfolder_platformservicefolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingrunfolder',
            name='scraping_run',
        ),
        migrations.DeleteModel(
            name='PlatformServiceFolder',
        ),
        migrations.DeleteModel(
            name='ScrapingRunFolder',
        ),
    ]
