# Generated by Django 5.2 on 2025-08-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_remove_scrapingrunfolder_scraping_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledscrapingtask',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledscrapingtask',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledscrapingtask',
            name='num_of_posts',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
