# Generated by Django 5.2 on 2025-08-09 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_accounts', '0019_tracksource_brightdata_config_and_more'),
        ('workflow', '0007_scheduledscrapingtask_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingjob',
            name='track_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraping_jobs', to='track_accounts.tracksource'),
        ),
    ]
