# Generated by Django 5.2 on 2025-08-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0021_remove_scrapeoutput_data_event_and_more'),
        ('workflow', '0008_scrapingjob_track_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingjob',
            name='track_source',
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='request_id',
            field=models.CharField(blank=True, help_text='BrightData request/snapshot ID for webhook mapping', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='scrapingjob',
            index=models.Index(fields=['request_id'], name='workflow_sc_request_1a8087_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapingjob',
            index=models.Index(fields=['batch_job', 'url'], name='workflow_sc_batch_j_bf787a_idx'),
        ),
    ]
