# Generated by Django 5.2 on 2025-08-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0022_scraperrequest_batch_run_and_more'),
        ('workflow', '0009_remove_scrapingjob_track_source_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scrapingjob',
            name='workflow_sc_request_1a8087_idx',
        ),
        migrations.RemoveIndex(
            model_name='scrapingjob',
            name='workflow_sc_batch_j_bf787a_idx',
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='snapshot_id',
            field=models.CharField(blank=True, help_text='BrightData snapshot ID for direct webhook mapping', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='webhook_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='webhook_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddIndex(
            model_name='scrapingjob',
            index=models.Index(fields=['snapshot_id'], name='workflow_sc_snapsho_818b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapingjob',
            index=models.Index(fields=['status'], name='workflow_sc_status_85a7ad_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapingjob',
            index=models.Index(fields=['platform', 'service_type'], name='workflow_sc_platfor_d2b74a_idx'),
        ),
    ]
