# Generated by Django 5.2 on 2025-08-10 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_accounts', '0020_remove_tracksource_brightdata_config_and_more'),
        ('workflow', '0010_remove_scrapingjob_workflow_sc_request_1a8087_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingjob',
            name='job_folder',
            field=models.ForeignKey(blank=True, help_text='Direct link to job folder for webhook routing', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraping_jobs', to='track_accounts.unifiedrunfolder'),
        ),
        migrations.CreateModel(
            name='ScrapeOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_snapshot_id', models.CharField(blank=True, help_text='BrightData snapshot ID', max_length=255, null=True)),
                ('webhook_received_at', models.DateTimeField(auto_now_add=True, help_text='When webhook was received')),
                ('platform', models.CharField(help_text='Platform (instagram, facebook, linkedin, tiktok)', max_length=50)),
                ('service_type', models.CharField(help_text='Service type (posts, comments, reels)', max_length=50)),
                ('raw_payload', models.JSONField(help_text='Complete raw JSON payload from BrightData webhook')),
                ('processed', models.BooleanField(default=False, help_text='Whether this output has been processed into platform-specific tables')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When this output was processed', null=True)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrape_outputs', to='track_accounts.unifiedrunfolder')),
                ('scrape_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_outputs', to='workflow.scrapingjob')),
            ],
            options={
                'verbose_name': 'Scrape Output',
                'verbose_name_plural': 'Scrape Outputs',
                'ordering': ['-webhook_received_at'],
                'indexes': [models.Index(fields=['scrape_job'], name='workflow_sc_scrape__5b7671_idx'), models.Index(fields=['job_folder'], name='workflow_sc_job_fol_935020_idx'), models.Index(fields=['webhook_snapshot_id'], name='workflow_sc_webhook_4e750c_idx'), models.Index(fields=['platform', 'service_type'], name='workflow_sc_platfor_e90741_idx'), models.Index(fields=['processed'], name='workflow_sc_process_c8e4df_idx')],
            },
        ),
    ]
