# Generated by Django 5.2 on 2025-08-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0023_remove_webhook_status_field'),
        ('workflow', '0012_remove_webhook_status_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeoutput',
            name='job_folder',
        ),
        migrations.RemoveField(
            model_name='scrapeoutput',
            name='scrape_job',
        ),
        migrations.RemoveIndex(
            model_name='scrapingjob',
            name='workflow_sc_snapsho_818b8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='scrapingjob',
            name='workflow_sc_status_85a7ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='scrapingjob',
            name='workflow_sc_platfor_d2b74a_idx',
        ),
        migrations.RemoveField(
            model_name='scrapingjob',
            name='job_folder',
        ),
        migrations.RemoveField(
            model_name='scrapingjob',
            name='snapshot_id',
        ),
        migrations.RemoveField(
            model_name='scrapingjob',
            name='webhook_received_at',
        ),
        migrations.AddIndex(
            model_name='scrapingjob',
            index=models.Index(fields=['request_id'], name='workflow_sc_request_1a8087_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapingjob',
            index=models.Index(fields=['batch_job', 'url'], name='workflow_sc_batch_j_bf787a_idx'),
        ),
        migrations.DeleteModel(
            name='ScrapeOutput',
        ),
    ]
