# Generated by Django 5.1.6 on 2025-05-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_project_authorized_users_project_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="slug",
            field=models.CharField(blank=True, max_length=28, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.CharField(blank=True, max_length=28, unique=True),
        ),
    ]
