# Generated by Django 5.1.6 on 2025-05-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_organization_slug_project_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="project",
            name="slug",
        ),
    ]
