# Generated by Django 5.2 on 2025-08-05 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_service_platform_platformservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=200)),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='active', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Company address', null=True)),
                ('website', models.URLField(blank=True, help_text='Company website', null=True)),
                ('industry', models.CharField(blank=True, help_text='Company industry', max_length=100, null=True)),
                ('size', models.CharField(blank=True, help_text='Company size (e.g., Small, Medium, Large)', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Company description', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person', max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact person email', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact person phone', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
