# Generated by Django 5.2 on 2025-08-07 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_simplify_company_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedUserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the user', max_length=255)),
                ('email', models.EmailField(help_text="User's email address", max_length=254, unique=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('tenant_admin', 'Tenant Admin'), ('user', 'User')], default='user', help_text="User's role in the system", max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', help_text="User's account status", max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='When the user record was created')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='When the user record was last updated')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified_users', to='users.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unified_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unified User Record',
                'verbose_name_plural': 'Unified User Records',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['email'], name='users_unifi_email_ab0c3a_idx'), models.Index(fields=['role'], name='users_unifi_role_efb96b_idx'), models.Index(fields=['status'], name='users_unifi_status_791e07_idx'), models.Index(fields=['company'], name='users_unifi_company_9ba007_idx'), models.Index(fields=['created_date'], name='users_unifi_created_54b348_idx')],
            },
        ),
    ]
