# Generated by Django 5.2 on 2025-08-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_unifieduserrecord'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='unifieduserrecord',
            name='users_unifi_email_ab0c3a_idx',
        ),
        migrations.AlterField(
            model_name='unifieduserrecord',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='When the user was created'),
        ),
        migrations.AlterField(
            model_name='unifieduserrecord',
            name='email',
            field=models.EmailField(blank=True, help_text="User's email address", max_length=254),
        ),
        migrations.AlterField(
            model_name='unifieduserrecord',
            name='name',
            field=models.CharField(blank=True, help_text='Full name of the user', max_length=255),
        ),
        migrations.AlterField(
            model_name='unifieduserrecord',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text="User's status", max_length=20),
        ),
    ]
