# Generated by Django 5.2 on 2025-08-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_unifieduserrecord_users_unifi_email_ab0c3a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name for this user in this organization', max_length=255, null=True),
        ),
    ]
