# Generated by Django 5.2 on 2025-09-29 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linkedin_data', '0001_initial'),
        ('track_accounts', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='scraping_run',
            field=models.ForeignKey(blank=True, help_text='Associated scraping run', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_folders', to='workflow.scrapingrun'),
        ),
        migrations.AddField(
            model_name='folder',
            name='unified_job_folder',
            field=models.ForeignKey(blank=True, help_text='Linked unified job folder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkedin_platform_folders', to='track_accounts.unifiedrunfolder'),
        ),
        migrations.AddField(
            model_name='linkedincomment',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='linkedin_data.folder'),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='linkedin_data.folder'),
        ),
        migrations.AddField(
            model_name='linkedincomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='linkedin_data.linkedinpost'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['unified_job_folder'], name='linkedin_da_unified_cc6108_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedinpost',
            index=models.Index(fields=['user_posted'], name='linkedin_da_user_po_be8340_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedinpost',
            index=models.Index(fields=['post_id'], name='linkedin_da_post_id_73fd15_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedinpost',
            index=models.Index(fields=['date_posted'], name='linkedin_da_date_po_3ff729_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedinpost',
            index=models.Index(fields=['user_id'], name='linkedin_da_user_id_b9e93f_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedinpost',
            index=models.Index(fields=['post_type'], name='linkedin_da_post_ty_af4c1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='linkedinpost',
            unique_together={('post_id', 'folder')},
        ),
        migrations.AddIndex(
            model_name='linkedincomment',
            index=models.Index(fields=['user_id'], name='linkedin_da_user_id_bcc3cd_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedincomment',
            index=models.Index(fields=['comment_date'], name='linkedin_da_comment_73cc3d_idx'),
        ),
    ]
