# Generated by Django 5.2 on 2025-08-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin_data', '0002_folder_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='category',
            field=models.CharField(choices=[('posts', 'Posts'), ('reels', 'Reels'), ('comments', 'Comments')], default='posts', help_text='Type of content stored in this folder', max_length=20),
        ),
    ]
