# Generated by Django 5.2 on 2025-08-06 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin_data', '0003_folder_category'),
        ('users', '0006_service_platform_platformservice'),
        ('workflow', '0006_remove_scrapingrunfolder_scraping_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_type',
            field=models.CharField(choices=[('run', 'Scraping Run'), ('service', 'Platform Service'), ('content', 'Content Folder')], default='content', help_text='Type of folder in the hierarchy', max_length=20),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, help_text='Parent folder in the hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='linkedin_data.folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='scraping_run',
            field=models.ForeignKey(blank=True, help_text='Associated scraping run', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_folders', to='workflow.scrapingrun'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='category',
            field=models.CharField(choices=[('posts', 'Posts'), ('comments', 'Comments')], default='posts', help_text='Type of content stored in this folder', max_length=20),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['folder_type', 'scraping_run'], name='linkedin_da_folder__8ed0ce_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent_folder', 'folder_type'], name='linkedin_da_parent__77b385_idx'),
        ),
    ]
