# Generated by Django 5.2 on 2025-08-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin_data', '0004_folder_folder_type_folder_parent_folder_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='folder',
            name='linkedin_da_folder__8ed0ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='folder',
            name='linkedin_da_parent__77b385_idx',
        ),
        migrations.AlterField(
            model_name='folder',
            name='category',
            field=models.CharField(choices=[('posts', 'Posts'), ('reels', 'Reels'), ('comments', 'Comments')], default='posts', help_text='Type of content stored in this folder', max_length=20),
        ),
    ]
