# Generated by Django 5.2 on 2025-08-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin_data', '0005_remove_folder_linkedin_da_folder__8ed0ce_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_type',
            field=models.CharField(choices=[('run', 'Scraping Run'), ('service', 'Platform Service'), ('content', 'Content Folder'), ('job', 'Job Folder')], default='content', help_text='Type of folder in the hierarchy', max_length=20),
        ),
    ]
