# Generated by Django 5.2 on 2025-08-10 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightdata_integration', '0022_scraperrequest_batch_run_and_more'),
        ('linkedin_data', '0010_folder_scrape_job_linkedinpost_scrape_job_and_more'),
        ('track_accounts', '0020_remove_tracksource_brightdata_config_and_more'),
        ('workflow', '0010_remove_scrapingjob_workflow_sc_request_1a8087_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinpost',
            name='job_folder',
            field=models.ForeignKey(blank=True, help_text='Direct link to job folder for webhook routing', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_posts', to='track_accounts.unifiedrunfolder'),
        ),
        migrations.AddIndex(
            model_name='linkedinpost',
            index=models.Index(fields=['scrape_job'], name='linkedin_da_scrape__d62ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedinpost',
            index=models.Index(fields=['scraper_request'], name='linkedin_da_scraper_b5b421_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedinpost',
            index=models.Index(fields=['webhook_snapshot_id'], name='linkedin_da_webhook_c675d9_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedinpost',
            index=models.Index(fields=['job_folder'], name='linkedin_da_job_fol_c53550_idx'),
        ),
    ]
