# Generated by Django 5.2 on 2025-08-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin_data', '0011_linkedinpost_job_folder_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='folder',
            name='linkedin_da_scrape__7b495e_idx',
        ),
        migrations.RemoveIndex(
            model_name='folder',
            name='linkedin_da_scrapin_adb0cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='linkedinpost',
            name='linkedin_da_scrape__d62ce0_idx',
        ),
        migrations.RemoveIndex(
            model_name='linkedinpost',
            name='linkedin_da_scraper_b5b421_idx',
        ),
        migrations.RemoveIndex(
            model_name='linkedinpost',
            name='linkedin_da_webhook_c675d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='linkedinpost',
            name='linkedin_da_job_fol_c53550_idx',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='scrape_job',
        ),
        migrations.RemoveField(
            model_name='linkedinpost',
            name='job_folder',
        ),
        migrations.RemoveField(
            model_name='linkedinpost',
            name='scrape_job',
        ),
        migrations.RemoveField(
            model_name='linkedinpost',
            name='scraper_request',
        ),
        migrations.RemoveField(
            model_name='linkedinpost',
            name='webhook_received_at',
        ),
        migrations.RemoveField(
            model_name='linkedinpost',
            name='webhook_snapshot_id',
        ),
        migrations.AlterField(
            model_name='folder',
            name='category',
            field=models.CharField(choices=[('posts', 'Posts'), ('reels', 'Reels'), ('comments', 'Comments')], default='posts', help_text='Type of content stored in this folder', max_length=20),
        ),
        migrations.AlterField(
            model_name='folder',
            name='folder_type',
            field=models.CharField(choices=[('run', 'Scraping Run'), ('platform', 'Platform'), ('service', 'Platform Service'), ('job', 'Job'), ('content', 'Content Folder')], default='content', help_text='Type of folder in the hierarchy', max_length=20),
        ),
    ]
